# Generated by Django 4.1.3 on 2022-11-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('price', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('paywall_id', models.CharField(max_length=200)),
            ],
        ),
    ]
